name: integration-build
on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: test-step
              run: echo "Hello World!"

            
